<?php

namespace App\Livewire\Home;

use Livewire\Component;
use App\Models\Jugadore;
use App\Models\JugadoresNumero;
use App\Models\Campeonato;
use DB;

class Champions extends Component
{
    public $id_jugador, $torneo=0, $categoria=0, $torneos=[], $categorias=[];
    public $tipo = 'bateador';

    public function updatedCategoria($value)
    {
        $this->torneo = null;
    }

    public function render()
    {
        $this->categorias = Campeonato::orderBy('categoria_id','asc')
        ->select('categorias.*','campeonatos.*','categorias.id as id')
        ->join('categorias', 'categorias.id', '=', 'campeonatos.categoria_id')
        ->get();

        $this->torneos = Campeonato::where('categoria_id', $this->categoria)->orderBy('fecha_inicio', 'desc')->get();

        $averages = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('porcentaje_bateo', 'desc')
        ->get();

        $hits = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('hit', 'desc')
        ->get();

        $dobles = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('dobles', 'desc')
        ->get();

        $triples = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('triples', 'desc')
        ->get();

        $jonrones = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('hr', 'desc')
        ->get();

        $anotadas = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('anotadas', 'desc')
        ->get();

        $impulsadas = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('rbi', 'desc')
        ->get();

        $robos = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('robadas', 'desc')
        ->get();

        $boletos = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('boletos_recibidos', 'desc')
        ->get();

        $efectividad = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('porcentaje_efectividad', 'asc')
        ->get();

        $ganados = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('ganados', 'desc')
        ->get();

        $ponches = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('ponches_propinados', 'desc')
        ->get();

        $innings = DB::table('jugadores_numeros')
        ->select('jugadores_numeros.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo'
        , DB::raw('sum(jugadores_numeros.juegos) as juegos')
        , DB::raw('sum(jugadores_numeros.hit) as hit')
        , DB::raw('sum(jugadores_numeros.dobles) as dobles')
        , DB::raw('sum(jugadores_numeros.triples) as triples')
        , DB::raw('sum(jugadores_numeros.hr) as hr')
        , DB::raw('sum(jugadores_numeros.anotadas) as anotadas')
        , DB::raw('sum(jugadores_numeros.rbi) as rbi')
        , DB::raw('sum(jugadores_numeros.robadas) as robadas')
        , DB::raw('sum(jugadores_numeros.boletos_recibidos) as boletos_recibidos')
        , DB::raw('((sum(jugadores_numeros.hit) * 1000) / sum(jugadores_numeros.vb)) as porcentaje_bateo')
        , DB::raw('(((sum(jugadores_numeros.hit) - sum(jugadores_numeros.dobles) - sum(jugadores_numeros.triples) - sum(jugadores_numeros.hr)) + (sum(jugadores_numeros.dobles) * 2) + (sum(jugadores_numeros.triples) * 3) + (sum(jugadores_numeros.hr) * 4)) / sum(jugadores_numeros.vb)) * 1000 as porcentaje_slugging')
        , DB::raw('sum(jugadores_numeros.j) as j')
        , DB::raw('sum(jugadores_numeros.ganados) as ganados')
        , DB::raw('sum(jugadores_numeros.perdidos) as perdidos')
        , DB::raw('sum(jugadores_numeros.ponches_propinados) as ponches_propinados')
        , DB::raw('sum(jugadores_numeros.ip) as ip')
        , DB::raw('((sum(jugadores_numeros.carreras_limpias) * 9) / sum(jugadores_numeros.ip)) as porcentaje_efectividad')
        , DB::raw('sum(jugadores_numeros.carreras_limpias) as carreras_limpias'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_numeros.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_numeros.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_numeros.categoria_id', $this->categoria)
        ->where('jugadores_numeros.campeonato_id', $this->torneo)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('ip', 'desc')
        ->get();

        $receptores = DB::table('jugadores_defensivas')
        ->select('jugadores_defensivas.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo','jugadores_defensivas.posicion as posicion'
        , DB::raw('sum(jugadores_defensivas.juegos) as juegos')
        , DB::raw('sum(jugadores_defensivas.innings) as innings')
        , DB::raw('sum(jugadores_defensivas.outs) as outs')
        , DB::raw('sum(jugadores_defensivas.asistencias) as asistencias')
        , DB::raw('sum(jugadores_defensivas.errores) as errores')
        , DB::raw('(( sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias)) / 
         (sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias) + sum(jugadores_defensivas.errores)))
         * 1000 as porcentaje_defensa'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_defensivas.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_defensivas.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_defensivas.categoria_id', $this->categoria)
        ->where('jugadores_defensivas.campeonato_id', $this->torneo)
        ->where('posicion', 2)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('porcentaje_defensa', 'desc')
        ->get();

        $primeras = DB::table('jugadores_defensivas')
        ->select('jugadores_defensivas.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo','jugadores_defensivas.posicion as posicion'
        , DB::raw('sum(jugadores_defensivas.juegos) as juegos')
        , DB::raw('sum(jugadores_defensivas.innings) as innings')
        , DB::raw('sum(jugadores_defensivas.outs) as outs')
        , DB::raw('sum(jugadores_defensivas.asistencias) as asistencias')
        , DB::raw('sum(jugadores_defensivas.errores) as errores')
        , DB::raw('(( sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias)) / 
         (sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias) + sum(jugadores_defensivas.errores)))
         * 1000 as porcentaje_defensa'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_defensivas.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_defensivas.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_defensivas.categoria_id', $this->categoria)
        ->where('jugadores_defensivas.campeonato_id', $this->torneo)
        ->where('posicion', 3)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('porcentaje_defensa', 'desc')
        ->get();

        $segundas = DB::table('jugadores_defensivas')
        ->select('jugadores_defensivas.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo','jugadores_defensivas.posicion as posicion'
        , DB::raw('sum(jugadores_defensivas.juegos) as juegos')
        , DB::raw('sum(jugadores_defensivas.innings) as innings')
        , DB::raw('sum(jugadores_defensivas.outs) as outs')
        , DB::raw('sum(jugadores_defensivas.asistencias) as asistencias')
        , DB::raw('sum(jugadores_defensivas.errores) as errores')
        , DB::raw('(( sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias)) / 
         (sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias) + sum(jugadores_defensivas.errores)))
         * 1000 as porcentaje_defensa'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_defensivas.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_defensivas.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_defensivas.categoria_id', $this->categoria)
        ->where('jugadores_defensivas.campeonato_id', $this->torneo)
        ->where('posicion', 4)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('porcentaje_defensa', 'desc')
        ->get();

        $terceras = DB::table('jugadores_defensivas')
        ->select('jugadores_defensivas.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo','jugadores_defensivas.posicion as posicion'
        , DB::raw('sum(jugadores_defensivas.juegos) as juegos')
        , DB::raw('sum(jugadores_defensivas.innings) as innings')
        , DB::raw('sum(jugadores_defensivas.outs) as outs')
        , DB::raw('sum(jugadores_defensivas.asistencias) as asistencias')
        , DB::raw('sum(jugadores_defensivas.errores) as errores')
        , DB::raw('(( sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias)) / 
         (sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias) + sum(jugadores_defensivas.errores)))
         * 1000 as porcentaje_defensa'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_defensivas.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_defensivas.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_defensivas.categoria_id', $this->categoria)
        ->where('jugadores_defensivas.campeonato_id', $this->torneo)
        ->where('posicion', 5)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('porcentaje_defensa', 'desc')
        ->get();

        $shorts = DB::table('jugadores_defensivas')
        ->select('jugadores_defensivas.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo','jugadores_defensivas.posicion as posicion'
        , DB::raw('sum(jugadores_defensivas.juegos) as juegos')
        , DB::raw('sum(jugadores_defensivas.innings) as innings')
        , DB::raw('sum(jugadores_defensivas.outs) as outs')
        , DB::raw('sum(jugadores_defensivas.asistencias) as asistencias')
        , DB::raw('sum(jugadores_defensivas.errores) as errores')
        , DB::raw('(( sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias)) / 
         (sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias) + sum(jugadores_defensivas.errores)))
         * 1000 as porcentaje_defensa'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_defensivas.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_defensivas.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_defensivas.categoria_id', $this->categoria)
        ->where('jugadores_defensivas.campeonato_id', $this->torneo)
        ->where('posicion', 6)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('porcentaje_defensa', 'desc')
        ->get();

        $lefts = DB::table('jugadores_defensivas')
        ->select('jugadores_defensivas.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo','jugadores_defensivas.posicion as posicion'
        , DB::raw('sum(jugadores_defensivas.juegos) as juegos')
        , DB::raw('sum(jugadores_defensivas.innings) as innings')
        , DB::raw('sum(jugadores_defensivas.outs) as outs')
        , DB::raw('sum(jugadores_defensivas.asistencias) as asistencias')
        , DB::raw('sum(jugadores_defensivas.errores) as errores')
        , DB::raw('(( sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias)) / 
         (sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias) + sum(jugadores_defensivas.errores)))
         * 1000 as porcentaje_defensa'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_defensivas.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_defensivas.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_defensivas.categoria_id', $this->categoria)
        ->where('jugadores_defensivas.campeonato_id', $this->torneo)
        ->where('posicion', 7)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('porcentaje_defensa', 'desc')
        ->get();

        $centers = DB::table('jugadores_defensivas')
        ->select('jugadores_defensivas.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo','jugadores_defensivas.posicion as posicion'
        , DB::raw('sum(jugadores_defensivas.juegos) as juegos')
        , DB::raw('sum(jugadores_defensivas.innings) as innings')
        , DB::raw('sum(jugadores_defensivas.outs) as outs')
        , DB::raw('sum(jugadores_defensivas.asistencias) as asistencias')
        , DB::raw('sum(jugadores_defensivas.errores) as errores')
        , DB::raw('(( sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias)) / 
         (sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias) + sum(jugadores_defensivas.errores)))
         * 1000 as porcentaje_defensa'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_defensivas.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_defensivas.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_defensivas.categoria_id', $this->categoria)
        ->where('jugadores_defensivas.campeonato_id', $this->torneo)
        ->where('posicion', 8)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('porcentaje_defensa', 'desc')
        ->get();

        $rights = DB::table('jugadores_defensivas')
        ->select('jugadores_defensivas.*','campeonatos.nombre as campeonato','jugadores.nombre as jugador','jugadores.equipo_id as equipo','equipos.nombre as nombre_equipo','jugadores_defensivas.posicion as posicion'
        , DB::raw('sum(jugadores_defensivas.juegos) as juegos')
        , DB::raw('sum(jugadores_defensivas.innings) as innings')
        , DB::raw('sum(jugadores_defensivas.outs) as outs')
        , DB::raw('sum(jugadores_defensivas.asistencias) as asistencias')
        , DB::raw('sum(jugadores_defensivas.errores) as errores')
        , DB::raw('(( sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias)) / 
         (sum(jugadores_defensivas.outs) + sum(jugadores_defensivas.asistencias) + sum(jugadores_defensivas.errores)))
         * 1000 as porcentaje_defensa'))
        ->join('campeonatos', 'campeonatos.id', '=', 'jugadores_defensivas.campeonato_id')
        ->join('jugadores', 'jugadores.id', '=', 'jugadores_defensivas.jugador_id')
        ->join('equipos', 'equipos.id', '=', 'jugadores.equipo_id')
        ->where('jugadores_defensivas.categoria_id', $this->categoria)
        ->where('jugadores_defensivas.campeonato_id', $this->torneo)
        ->where('posicion', 9)
        ->LIMIT(10)
        ->groupBy('jugador_id')
        ->orderBy('porcentaje_defensa', 'desc')
        ->get();

        return view('livewire.home.champions')->with('averages', $averages)->with('hits', $hits)->with('dobles', $dobles)->with('triples', $triples)->with('jonrones', $jonrones)->with('anotadas', $anotadas)->with('impulsadas', $impulsadas)->with('robos', $robos)->with('boletos', $boletos)->with('efectividad', $efectividad)->with('ganados', $ganados)->with('ponches', $ponches)->with('innings', $innings)->with('receptores', $receptores)->with('primeras', $primeras)->with('segundas', $segundas)->with('terceras', $terceras)->with('shorts', $shorts)->with('lefts', $lefts)->with('centers', $centers)->with('rights', $rights);
    }
}
